[workspace]

members = [
  "./app",
  "./stock-data-providers",
  "./apps/mistletoe",
  "./data-sources/binance",
  "./data-sources/sources-common",
  "./data-sources/market-feed",
  "./connectivity/tg-bot-test",
  "./connectivity/tg-api",
  "./connectivity/tg-reporter",
]
